name: "Build and Push Docker Image"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Log in to Docker Hub"
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.MYUSERNAME }} --password-stdin

      - name: "Build Docker image"
        run: docker build -t ${{ secrets.MYUSERNAME }}/myflaskapp:latest .

      - name: "Push Docker image"
        run: docker push ${{ secrets.MYUSERNAME }}/myflaskapp:latest
